### ISSUE TITLE
Fix circular import

### ISSUE THREAD

**Issue by zuhanit** [zuhanit/epscript-lsp#2]
Current server(1.0.3) cannot deal with `Circular Import Problem`. See #1 
```javascript
// a
import b;

// b
import a;
```
If server meet codes like above, `baseListener` calls `enterImportStatement` continously, then server got panic with Maximum call stack exceed error.

**Comment by zuhanit** [comment]
check #1

**Comment by Chromowolf** [comment]
Hi zuhanit,

If I open `SCATool.eps` in the EE3 folder, I got "Maximum call stack size exceeded":
```
epScript Server initializing...
i18next: languageChanged en
i18next: initialized {
  debug: true,
  initImmediate: true,
  ns: [ 'translation' ],
  defaultNS: [ 'translation' ],
  fallbackLng: [ 'dev' ],
  fallbackNS: false,
  supportedLngs: false,
  nonExplicitSupportedLngs: false,
  load: 'all',
  preload: false,
  simplifyPluralSuffix: true,
  keySeparator: '.',
  nsSeparator: ':',
  pluralSeparator: '_',
  contextSeparator: '_',
  partialBundledLanguages: false,
  saveMissing: false,
  updateMissing: false,
  saveMissingTo: 'fallback',
  saveMissingPlurals: true,
  missingKeyHandler: false,
  missingInterpolationHandler: false,
  postProcess: false,
  postProcessPassResolved: false,
  returnNull: true,
  returnEmptyString: true,
  returnObjects: false,
  joinArrays: false,
  returnedObjectHandler: false,
  parseMissingKeyHandler: false,
  appendNamespaceToMissingKey: false,
  appendNamespaceToCIMode: false,
  overloadTranslationOptionHandler: [Function: overloadTranslationOptionHandler],
  interpolation: {
    escapeValue: true,
    format: [Function: bound value],
    prefix: '{{',
    suffix: '}}',
    formatSeparator: ',',
    unescapePrefix: '-',
    nestingPrefix: '$t(',
    nestingSuffix: ')',
    nestingOptionsSeparator: ',',
    maxReplaces: 1000,
    skipOnVariables: true
  },
  lng: 'en',
  resources: { en: { translation: [Object] }, ko: { translation: [Object] } },
  ignoreJSONStructure: true
}
Analyzer Initialized
I got those workspaceFolders:  null
Server registered, passed time: 0.022 seconds
{
  listen: [Function: listen],
  sendRequest: [Function: sendRequest],
  onRequest: [Function: onRequest],
  sendNotification: [Function: sendNotification],
  onNotification: [Function: onNotification],
  onProgress: [Function: onProgress],
  sendProgress: [Function: sendProgress],
  onInitialize: [Function: onInitialize],
  onInitialized: [Function: onInitialized],
  onShutdown: [Function: onShutdown],
  onExit: [Function: onExit],
  console: [Getter],
  telemetry: [Getter],
  tracer: [Getter],
  client: [Getter],
  window: [Getter],
  workspace: [Getter],
  languages: [Getter],
  onDidChangeConfiguration: [Function: onDidChangeConfiguration],
  onDidChangeWatchedFiles: [Function: onDidChangeWatchedFiles],
  __textDocumentSync: 1,
  onDidOpenTextDocument: [Function: onDidOpenTextDocument],
  onDidChangeTextDocument: [Function: onDidChangeTextDocument],
  onDidCloseTextDocument: [Function: onDidCloseTextDocument],
  onWillSaveTextDocument: [Function: onWillSaveTextDocument],
  onWillSaveTextDocumentWaitUntil: [Function: onWillSaveTextDocumentWaitUntil],
  onDidSaveTextDocument: [Function: onDidSaveTextDocument],
  sendDiagnostics: [Function: sendDiagnostics],
  onHover: [Function: onHover],
  onCompletion: [Function: onCompletion],
  onCompletionResolve: [Function: onCompletionResolve],
  onSignatureHelp: [Function: onSignatureHelp],
  onDeclaration: [Function: onDeclaration],
  onDefinition: [Function: onDefinition],
  onTypeDefinition: [Function: onTypeDefinition],
  onImplementation: [Function: onImplementation],
  onReferences: [Function: onReferences],
  onDocumentHighlight: [Function: onDocumentHighlight],
  onDocumentSymbol: [Function: onDocumentSymbol],
  onWorkspaceSymbol: [Function: onWorkspaceSymbol],
  onCodeAction: [Function: onCodeAction],
  onCodeActionResolve: [Function: onCodeActionResolve],
  onCodeLens: [Function: onCodeLens],
  onCodeLensResolve: [Function: onCodeLensResolve],
  onDocumentFormatting: [Function: onDocumentFormatting],
  onDocumentRangeFormatting: [Function: onDocumentRangeFormatting],
  onDocumentOnTypeFormatting: [Function: onDocumentOnTypeFormatting],
  onRenameRequest: [Function: onRenameRequest],
  onPrepareRename: [Function: onPrepareRename],
  onDocumentLinks: [Function: onDocumentLinks],
  onDocumentLinkResolve: [Function: onDocumentLinkResolve],
  onDocumentColor: [Function: onDocumentColor],
  onColorPresentation: [Function: onColorPresentation],
  onFoldingRanges: [Function: onFoldingRanges],
  onSelectionRanges: [Function: onSelectionRanges],
  onExecuteCommand: [Function: onExecuteCommand],
  dispose: [Function: dispose]
}
Capabilities Get
Server Initialized at 2022. 8. 16.
TextDocument: {
  _documents: [Object: null prototype] {},
  _configuration: {
    create: [Function (anonymous)],
    update: [Function (anonymous)],
    applyEdits: [Function (anonymous)]
  },
  _onDidChangeContent: i {
    _options: undefined,
    _event: [Function (anonymous)],
    _callbacks: a { _callbacks: [Array], _contexts: [Array] }
  },
  _onDidOpen: i { _options: undefined },
  _onDidClose: i { _options: undefined },
  _onDidSave: i { _options: undefined },
  _onWillSave: i { _options: undefined }
}
Uncaught exception received.
RangeError: Maximum call stack size exceeded
    at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466629)
    at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
    at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
    at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
    at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
    at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
    at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
    at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
    at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
    at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
[Error - 10:06:23 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Maximum call stack size exceeded
  Code: -32603 
[Error - 10:06:23 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Maximum call stack size exceeded
  Code: -32603 
[Error - 10:06:24 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Maximum call stack size exceeded
  Code: -32603 
[Error - 10:06:24 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Maximum call stack size exceeded
  Code: -32603 
[Error - 10:06:24 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Maximum call stack size exceeded
  Code: -32603 

```

This error constantly pops up when I edit the file, and is annoying. Is this related to the bug you mentioned above?

**Comment by zuhanit** [comment]
> Hi zuhanit,
> 
> If I open `SCATool.eps` in the EE3 folder, I got "Maximum call stack size exceeded":
> ```
> epScript Server initializing...
> i18next: languageChanged en
> i18next: initialized {
>   debug: true,
>   initImmediate: true,
>   ns: [ 'translation' ],
>   defaultNS: [ 'translation' ],
>   fallbackLng: [ 'dev' ],
>   fallbackNS: false,
>   supportedLngs: false,
>   nonExplicitSupportedLngs: false,
>   load: 'all',
>   preload: false,
>   simplifyPluralSuffix: true,
>   keySeparator: '.',
>   nsSeparator: ':',
>   pluralSeparator: '_',
>   contextSeparator: '_',
>   partialBundledLanguages: false,
>   saveMissing: false,
>   updateMissing: false,
>   saveMissingTo: 'fallback',
>   saveMissingPlurals: true,
>   missingKeyHandler: false,
>   missingInterpolationHandler: false,
>   postProcess: false,
>   postProcessPassResolved: false,
>   returnNull: true,
>   returnEmptyString: true,
>   returnObjects: false,
>   joinArrays: false,
>   returnedObjectHandler: false,
>   parseMissingKeyHandler: false,
>   appendNamespaceToMissingKey: false,
>   appendNamespaceToCIMode: false,
>   overloadTranslationOptionHandler: [Function: overloadTranslationOptionHandler],
>   interpolation: {
>     escapeValue: true,
>     format: [Function: bound value],
>     prefix: '{{',
>     suffix: '}}',
>     formatSeparator: ',',
>     unescapePrefix: '-',
>     nestingPrefix: '$t(',
>     nestingSuffix: ')',
>     nestingOptionsSeparator: ',',
>     maxReplaces: 1000,
>     skipOnVariables: true
>   },
>   lng: 'en',
>   resources: { en: { translation: [Object] }, ko: { translation: [Object] } },
>   ignoreJSONStructure: true
> }
> Analyzer Initialized
> I got those workspaceFolders:  null
> Server registered, passed time: 0.022 seconds
> {
>   listen: [Function: listen],
>   sendRequest: [Function: sendRequest],
>   onRequest: [Function: onRequest],
>   sendNotification: [Function: sendNotification],
>   onNotification: [Function: onNotification],
>   onProgress: [Function: onProgress],
>   sendProgress: [Function: sendProgress],
>   onInitialize: [Function: onInitialize],
>   onInitialized: [Function: onInitialized],
>   onShutdown: [Function: onShutdown],
>   onExit: [Function: onExit],
>   console: [Getter],
>   telemetry: [Getter],
>   tracer: [Getter],
>   client: [Getter],
>   window: [Getter],
>   workspace: [Getter],
>   languages: [Getter],
>   onDidChangeConfiguration: [Function: onDidChangeConfiguration],
>   onDidChangeWatchedFiles: [Function: onDidChangeWatchedFiles],
>   __textDocumentSync: 1,
>   onDidOpenTextDocument: [Function: onDidOpenTextDocument],
>   onDidChangeTextDocument: [Function: onDidChangeTextDocument],
>   onDidCloseTextDocument: [Function: onDidCloseTextDocument],
>   onWillSaveTextDocument: [Function: onWillSaveTextDocument],
>   onWillSaveTextDocumentWaitUntil: [Function: onWillSaveTextDocumentWaitUntil],
>   onDidSaveTextDocument: [Function: onDidSaveTextDocument],
>   sendDiagnostics: [Function: sendDiagnostics],
>   onHover: [Function: onHover],
>   onCompletion: [Function: onCompletion],
>   onCompletionResolve: [Function: onCompletionResolve],
>   onSignatureHelp: [Function: onSignatureHelp],
>   onDeclaration: [Function: onDeclaration],
>   onDefinition: [Function: onDefinition],
>   onTypeDefinition: [Function: onTypeDefinition],
>   onImplementation: [Function: onImplementation],
>   onReferences: [Function: onReferences],
>   onDocumentHighlight: [Function: onDocumentHighlight],
>   onDocumentSymbol: [Function: onDocumentSymbol],
>   onWorkspaceSymbol: [Function: onWorkspaceSymbol],
>   onCodeAction: [Function: onCodeAction],
>   onCodeActionResolve: [Function: onCodeActionResolve],
>   onCodeLens: [Function: onCodeLens],
>   onCodeLensResolve: [Function: onCodeLensResolve],
>   onDocumentFormatting: [Function: onDocumentFormatting],
>   onDocumentRangeFormatting: [Function: onDocumentRangeFormatting],
>   onDocumentOnTypeFormatting: [Function: onDocumentOnTypeFormatting],
>   onRenameRequest: [Function: onRenameRequest],
>   onPrepareRename: [Function: onPrepareRename],
>   onDocumentLinks: [Function: onDocumentLinks],
>   onDocumentLinkResolve: [Function: onDocumentLinkResolve],
>   onDocumentColor: [Function: onDocumentColor],
>   onColorPresentation: [Function: onColorPresentation],
>   onFoldingRanges: [Function: onFoldingRanges],
>   onSelectionRanges: [Function: onSelectionRanges],
>   onExecuteCommand: [Function: onExecuteCommand],
>   dispose: [Function: dispose]
> }
> Capabilities Get
> Server Initialized at 2022. 8. 16.
> TextDocument: {
>   _documents: [Object: null prototype] {},
>   _configuration: {
>     create: [Function (anonymous)],
>     update: [Function (anonymous)],
>     applyEdits: [Function (anonymous)]
>   },
>   _onDidChangeContent: i {
>     _options: undefined,
>     _event: [Function (anonymous)],
>     _callbacks: a { _callbacks: [Array], _contexts: [Array] }
>   },
>   _onDidOpen: i { _options: undefined },
>   _onDidClose: i { _options: undefined },
>   _onDidSave: i { _options: undefined },
>   _onWillSave: i { _options: undefined }
> }
> Uncaught exception received.
> RangeError: Maximum call stack size exceeded
>     at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466629)
>     at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
>     at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
>     at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
>     at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
>     at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
>     at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
>     at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
>     at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
>     at e.appendContext (c:\Users\PCsPC\.vscode\extensions\zuhanit.eps-server-1.0.9\server\dist\server.js:2:466665)
> [Error - 10:06:23 PM] Request textDocument/documentSymbol failed.
>   Message: Request textDocument/documentSymbol failed with message: Maximum call stack size exceeded
>   Code: -32603 
> [Error - 10:06:23 PM] Request textDocument/documentSymbol failed.
>   Message: Request textDocument/documentSymbol failed with message: Maximum call stack size exceeded
>   Code: -32603 
> [Error - 10:06:24 PM] Request textDocument/documentSymbol failed.
>   Message: Request textDocument/documentSymbol failed with message: Maximum call stack size exceeded
>   Code: -32603 
> [Error - 10:06:24 PM] Request textDocument/documentSymbol failed.
>   Message: Request textDocument/documentSymbol failed with message: Maximum call stack size exceeded
>   Code: -32603 
> [Error - 10:06:24 PM] Request textDocument/documentSymbol failed.
>   Message: Request textDocument/documentSymbol failed with message: Maximum call stack size exceeded
>   Code: -32603 
> 
> ```
> 
> This error constantly pops up when I edit the file, and is annoying. Is this related to the bug you mentioned above?

Yes. Most case of this bug occurred in EE3 project. I know this is very important issue for user, but I don't have a idea to solve this. 😥

To avoid this bug temporarily, Handwrite your own euddraft configuration file. But you can't use EE3's built-in functions like SCA, MusicPlayer sadly.
