### ISSUE TITLE
error popup when doing variable = variable

### ISSUE THREAD

**Issue by divinebeam** [zuhanit/epscript-lsp#27]
when typing variable = variable, without having finished the statement, an error pops up
https://puu.sh/JoSQN/9d36895323.png

and also in console
"[Error - 6:48:08 p.m.] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Maximum call stack size exceeded
  Code: -32603 "

obviously not a huge issue but never encountered this before even though I've typed similar things before.

**Comment by zuhanit** [comment]
Got it, but it takes a while to solve until I rewrite AST building method. Thank you for your report!

**Comment by zuhanit** [comment]
Fixed in https://github.com/zuhanit/epscript-lsp/commit/a605d4817f972e51a1e8900596449a1b46a6828c

tmi: I want to rewrite AST building method, but I ain't got no time. :(
