### ISSUE TITLE
Binary representation of number (`0b11110011`) is causing problem

### ISSUE THREAD

**Issue by Chromowolf** [zuhanit/epscript-lsp#34]
If there is binary number in the code, such as:
`MemoryX(0x57F23C, Exactly, 0, 0b111111)`
Then eps-server won't show any prompt

**Comment by zuhanit** [comment]
Binary literal has added in euddraft 0.9.8.1 so it doesn't included in `epScriptLexer.g4` and `epScriptParser.g4`. Similar to #28. I'll fix it. Thank you for report!

**Comment by zuhanit** [comment]
Fixed in https://github.com/zuhanit/epscript-lsp/commit/c7b2a76b2629231f786eed5672907e48e3b6007c.
