### ISSUE TITLE
Cannot provide symbol info properly

### ISSUE THREAD

**Issue by zuhanit** [zuhanit/epscript-lsp#37]
- `Hover`
- `Go to definition`

Those above language features, the server uses `getSymbolByName` internally. It can causes some problems. Instead using `evaluateNode` to get more accurate symbol.

**Comment by Chromowolf** [comment]
Is this issue same as what I've experiencing here?
![image](https://user-images.githubusercontent.com/37732663/203301810-9d60706f-20c9-4431-869a-861c40f7478c.png)

**Comment by zuhanit** [comment]
> Is this issue same as what I've experiencing here? ![image](https://user-images.githubusercontent.com/37732663/203301810-9d60706f-20c9-4431-869a-861c40f7478c.png)

Your issue is related to #27. I guess it caused in `Evaluating` sequence. Might you use same variable in epxression, like below?

```ts
const v = 1;
const v = v ? 1;
```

Of course it's correct code, but there's something wrong with eps-server. I want to solve this after rewriting AST build and Symbol Implementation because current code is messy so I'ts hard to handle them :(

**Comment by zuhanit** [comment]
Fixed in https://github.com/zuhanit/epscript-lsp/commit/a605d4817f972e51a1e8900596449a1b46a6828c
