### ISSUE TITLE
Support public class attributes and `@classmethod`

### ISSUE THREAD

**Issue by armoha** [zuhanit/epscript-lsp#43]
For example, `CUnit` class has `@classmethod` `CUnit.from_read(EPDaddress)`, `CUnit.from_ptr(ptrValue)` as additional constructors, and also `CUnit` has various [descriptors](https://docs.python.org/3/glossary.html#term-descriptor) (See https://github.com/armoha/eudplib/blob/master/eudplib/offsetmap/cunit.py#L88-L371).

Currently, eps-server only autocompletes instance methods, arguments of `__init__`, and does not show public `@property` or attributes:
https://github.com/zuhanit/epscript-lsp/blob/master/packages/server/src/lib/json/class.json#L889-L7984

- [x] #46
- [ ] Autocomplete public `@classmethod`, `@staticmethod`
- [ ] Autocomplete public `@property` and descriptors.
- [ ] Hide private instance methods (name starts with `_`)

**Comment by zuhanit** [comment]
I considered hide private methods, but in VS Code python extension shows private method starts with _. In next version private and protected methods will be now prompted in completion.
