### ISSUE TITLE
No auto-completion for `CurrentPlayer` in `CreateUnit` (v1.2.10)

### ISSUE THREAD

**Issue by Chromowolf** [zuhanit/epscript-lsp#45]
![image](https://user-images.githubusercontent.com/37732663/229776364-40875456-47b3-4f6b-9d49-93025c13c9f8.png)
There's no output in the console

**Comment by zuhanit** [comment]
Does it happens only `CreateUnit`, or every function argument type completions are buggy?

**Comment by zuhanit** [comment]
Fixed in https://github.com/zuhanit/epscript-lsp/commit/5b45a7637793d3e4a7e1fc60e07a9195df689427
